import localFont from "next/font/local";
import "./globals.css";

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Reviewer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
        <script src="https://unpkg.com/scrollreveal"></script>
      </head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 
          max-md:bg-posa max-md:bg-right max-md:bg-cover
          bg-totoro bg-[length:150%_auto] bg-no-repeat bg-right-bottom`}
      >
        {children}
      </body>
    </html>
  );
}
